---
# roles/was/tasks/create_dmgr_profile.yml
# @version v1.05_2023-MAR-13
# @author Kevin Jeffery

- name: Create {{ profile_item.profile_name }} Profile
  wasprofile:
    was_home: "{{ was_home }}"
    action: "create"
    profile_name: "{{ profile_item.profile_name }}"
    username: "{{ was_admin_id }}"
    password: "{{ was_admin_pwd }}"
    profile_path: "{{ profile_item.profile_path | default(was_home + '/profiles/' + profile_item.profile_name) }}"
    profile_type: "dmgr"
    profile_params: "{{ profile_item.profile_params | default(was_ndm_params) }}"
  become: yes
  register: ret_create
  tags: always

- name: Set SOAP Request Timeout
  lineinfile:
    dest: "{{ profile_item.profile_path | default(was_home + '/profiles/' + profile_item.profile_name) }}/properties/soap.client.props"
    regexp: '^com\.ibm\.SOAP\.requestTimeout=1800'
    line: "com.ibm.SOAP.requestTimeout=1800"
  become: yes
  tags: always

- name: Deploy CA Certificate
  include_tasks: configure_cacert.yml
  vars:
    was_truststore: "{{ was_profile_home }}/{{ was_ndm_profile }}/etc/trust.p12"
    was_cacert_dest: "{{ was_profile_home }}/{{ was_ndm_profile }}/etc/{{ idmca_env }}.cer"
  tags: always

- name: Start Deployment Manager
  command: "{{ was_profile_home }}/{{ profile_item.profile_name }}/bin/startManager.sh"
  become: yes
  when: ret_create.changed
  register: ret_start
  tags: always

- name: Configure Logging
  vars:
    was_profile_name: "{{ was_ndm_profile }}"
    was_node_name: dmgr
  include_tasks: relocate_logs.yml
  when: was_log_directory is defined
  tags: always

- name: Stop Deployment Manager
  command: "{{ was_profile_home }}/{{ profile_item.profile_name }}/bin/stopManager.sh -username {{ was_admin_id }} -password {{ was_admin_pwd }}"
  become: yes
  when: ret_start.changed
  tags: always

- name: Service variables
  set_fact:
    was_service_pidpath: "{{ (was_profile_home + '/' + was_ndm_profile + '/logs') if was_log_directory is not defined else was_log_directory + '/dmgr' }}"
  tags: always

- name: Deploy Dmgr Service file
  vars:
    was_service_description: "Deployment Manager - {{ was_ndm_profile }}"
    was_service_pidfile: "{{ was_service_pidpath }}/dmgr/dmgr.pid"
    was_service_exec_start: "{{ was_profile_home }}/{{ was_ndm_profile }}/bin/startManager.sh"
    was_service_exec_stop: "{{ was_profile_home }}/{{ was_ndm_profile }}/bin/stopManager.sh"
  template:
    src: "was.service.j2"
    dest: "/etc/systemd/system/{{ was_ndm_profile }}.service"
    force: yes
    owner: "{{ ansible_user }}"
  become: "yes"
  notify:
  - Enable Dmgr Service
  tags: always

- meta: flush_handlers
  tags: always
