---
# roles/was/tasks/unconfigure_plugin.yml
# @version v1.01_2023-APR-11
# @author Kevin Jeffery

- name: Stop IHS servers
  command: "{{ http_home }}/bin/apachectl stop"
  become: yes
  tags: always

- name: Remove Plugin configuration
  lineinfile:
    path: "{{ http_home }}/conf/httpd.conf"
    regex: "{{ item }}"
    state: absent
  loop:
  - ^LoadModule was_ap24_module
  - ^WebSpherePluginConfig
  become: yes
  tags: always

- name: Remove Plugin config directory
  file:
    path: "{{ plugins_home }}/config/{{ http_server_name }}"
    state: absent
  become: yes
  tags: always

- name: Remove Plugin response file
  file:
    path: "{{ http_home }}/conf/was_plugin.txt"
    state: absent
  become: yes
  tags: always
